### PR TITLE
Python cleanup

### PR DESCRIPTION
**Pull request by m3brown**
- Remove a couple unused functions (`fetchLibraries`, `removeOfflineFiles`) that seems to be unrelated to the repo's purpose.
- Refactor the for loop in main() to be a little more DRY
- Pull the session logic outside of the while loop in fetchAssets, which should have some amount (possibly negligable) performance improvement

### CODE REVIEW

**Review by tenekev — APPROVED** [review]

**Review by tenekev — APPROVED** [review]
Thanks. I reused the Immich class from my other tool for removing offline files.

I'm wondering if uniting them in a single repo and importing the Immich class from a reusable module is a better approach. I'm no a dev.

**Review by tenekev — APPROVED** [review]
Thanks. So silly of me.

**Comment by m3brown** [comment]
> Thanks. I reused the Immich class from my other tool for removing offline files.
> 
> I'm wondering if uniting them in a single repo and importing the Immich class from a reusable module is a better approach.

I think there's value in both approaches.

Good: Less copy-pasting of similar functionality across repos

Bad: Complicated runtime process. Is there one dockerfile per app? Or one docker build that you call differently depending on your need? The README might become long and messy.

There is prior art of a single repo approach here: https://github.com/Willena/immich-tools/tree/master


> I'm no a dev.

It's awesome that you've put this together, especially if you're not a developer. This is good stuff. Seriously, a high five from me. Nothing in this PR was "silly of you", working together is how we get a better result.

**Comment by tenekev** [comment]
I've seen Willena's Repo but it didn't cover all my needs. TS is not my forte and the complexity of the repo put me off entirely. The ENV variable alone will be a mess. That's why my tools are separate and I guess I'll keep them that way, for now at least.

> It's awesome that you've put this together, especially if you're not a developer. 

Thank you, I've thought about working as a dev, especially with Python because I love it. I've always been apprehensive about my skills though - I'm entirely self-taught. Heck, this is my first merged PR ever. Your praise means a lot to me, really. I'll definitely pick up a thing or two from your PRs.

I'm closing this and will go over the other PRs.

**Pull request merged**
